//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EmbTask
{
    [Serializable]
    public class BatteryStateMsg : Message
    {
        public const string k_RosMessageName = "emb_task_msgs/BatteryState";
        public override string RosMessageName => k_RosMessageName;

        public BatteryInfoMsg[] batteries_states;

        public BatteryStateMsg()
        {
            this.batteries_states = new BatteryInfoMsg[0];
        }

        public BatteryStateMsg(BatteryInfoMsg[] batteries_states)
        {
            this.batteries_states = batteries_states;
        }

        public static BatteryStateMsg Deserialize(MessageDeserializer deserializer) => new BatteryStateMsg(deserializer);

        private BatteryStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.batteries_states, BatteryInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.batteries_states);
            serializer.Write(this.batteries_states);
        }

        public override string ToString()
        {
            return "BatteryStateMsg: " +
            "\nbatteries_states: " + System.String.Join(", ", batteries_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
