//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EmbTask
{
    [Serializable]
    public class BatteryInfoMsg : Message
    {
        public const string k_RosMessageName = "emb_task_msgs/BatteryInfo";
        public override string RosMessageName => k_RosMessageName;

        public const string IDLE = "idle";
        public const string CHARGING = "charging";
        public const string DISCHARGING = "discharging";
        public const string FULL = "full";
        public string charge_status;
        // 充放电状态
        public float voltage;
        // 电池总电压
        public float current;
        // 电池总电流
        public float temperature;
        // 电池温度
        public float maxdifvol;
        // 最大压差
        public float batsoc;
        // 电池总容量
        public float remainchargetime;
        // 剩余充电时间
        public ushort healthstatus;
        // 健康状态
        public float remainuselife;
        // 电池剩余寿命(循环周期数)

        public BatteryInfoMsg()
        {
            this.charge_status = "";
            this.voltage = 0.0f;
            this.current = 0.0f;
            this.temperature = 0.0f;
            this.maxdifvol = 0.0f;
            this.batsoc = 0.0f;
            this.remainchargetime = 0.0f;
            this.healthstatus = 0;
            this.remainuselife = 0.0f;
        }

        public BatteryInfoMsg(string charge_status, float voltage, float current, float temperature, float maxdifvol, float batsoc, float remainchargetime, ushort healthstatus, float remainuselife)
        {
            this.charge_status = charge_status;
            this.voltage = voltage;
            this.current = current;
            this.temperature = temperature;
            this.maxdifvol = maxdifvol;
            this.batsoc = batsoc;
            this.remainchargetime = remainchargetime;
            this.healthstatus = healthstatus;
            this.remainuselife = remainuselife;
        }

        public static BatteryInfoMsg Deserialize(MessageDeserializer deserializer) => new BatteryInfoMsg(deserializer);

        private BatteryInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.charge_status);
            deserializer.Read(out this.voltage);
            deserializer.Read(out this.current);
            deserializer.Read(out this.temperature);
            deserializer.Read(out this.maxdifvol);
            deserializer.Read(out this.batsoc);
            deserializer.Read(out this.remainchargetime);
            deserializer.Read(out this.healthstatus);
            deserializer.Read(out this.remainuselife);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.charge_status);
            serializer.Write(this.voltage);
            serializer.Write(this.current);
            serializer.Write(this.temperature);
            serializer.Write(this.maxdifvol);
            serializer.Write(this.batsoc);
            serializer.Write(this.remainchargetime);
            serializer.Write(this.healthstatus);
            serializer.Write(this.remainuselife);
        }

        public override string ToString()
        {
            return "BatteryInfoMsg: " +
            "\ncharge_status: " + charge_status.ToString() +
            "\nvoltage: " + voltage.ToString() +
            "\ncurrent: " + current.ToString() +
            "\ntemperature: " + temperature.ToString() +
            "\nmaxdifvol: " + maxdifvol.ToString() +
            "\nbatsoc: " + batsoc.ToString() +
            "\nremainchargetime: " + remainchargetime.ToString() +
            "\nhealthstatus: " + healthstatus.ToString() +
            "\nremainuselife: " + remainuselife.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
