//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EmbTask
{
    [Serializable]
    public class InnerDataMsg : Message
    {
        public const string k_RosMessageName = "emb_task_msgs/InnerData";
        public override string RosMessageName => k_RosMessageName;

        public float adc_orin_value;
        public float adc_orin_ibus_value;
        // Orin电流  A
        public float adc_arm_ibus_value;
        public float adc_ibus_value;
        public float adc_leftleg_ibus_value;
        public float adc_rightleg_ibus_value;
        public float adc_waist_ibus_value;
        // 腰部电流 A
        public float adc_charge_det_value;
        public float adc_vdc1_value;
        public float adc_mos_temp;
        public float adc_1v5;
        public float temptature;
        public float vrefint;
        public float adc_x86_ibus_value;
        // x86电流    A
        public float adc_rk_ibus_value;
        // rk电流  A
        public float adc_3vref_value;
        // 3v参考电压  V
        public ushort err_code;
        public byte second;
        // 秒
        public byte minute;
        // 分
        public byte hour;
        // 时
        public byte day;
        // 日
        public byte month;
        // 月
        public ushort year;
        // 年

        public InnerDataMsg()
        {
            this.adc_orin_value = 0.0f;
            this.adc_orin_ibus_value = 0.0f;
            this.adc_arm_ibus_value = 0.0f;
            this.adc_ibus_value = 0.0f;
            this.adc_leftleg_ibus_value = 0.0f;
            this.adc_rightleg_ibus_value = 0.0f;
            this.adc_waist_ibus_value = 0.0f;
            this.adc_charge_det_value = 0.0f;
            this.adc_vdc1_value = 0.0f;
            this.adc_mos_temp = 0.0f;
            this.adc_1v5 = 0.0f;
            this.temptature = 0.0f;
            this.vrefint = 0.0f;
            this.adc_x86_ibus_value = 0.0f;
            this.adc_rk_ibus_value = 0.0f;
            this.adc_3vref_value = 0.0f;
            this.err_code = 0;
            this.second = 0;
            this.minute = 0;
            this.hour = 0;
            this.day = 0;
            this.month = 0;
            this.year = 0;
        }

        public InnerDataMsg(float adc_orin_value, float adc_orin_ibus_value, float adc_arm_ibus_value, float adc_ibus_value, float adc_leftleg_ibus_value, float adc_rightleg_ibus_value, float adc_waist_ibus_value, float adc_charge_det_value, float adc_vdc1_value, float adc_mos_temp, float adc_1v5, float temptature, float vrefint, float adc_x86_ibus_value, float adc_rk_ibus_value, float adc_3vref_value, ushort err_code, byte second, byte minute, byte hour, byte day, byte month, ushort year)
        {
            this.adc_orin_value = adc_orin_value;
            this.adc_orin_ibus_value = adc_orin_ibus_value;
            this.adc_arm_ibus_value = adc_arm_ibus_value;
            this.adc_ibus_value = adc_ibus_value;
            this.adc_leftleg_ibus_value = adc_leftleg_ibus_value;
            this.adc_rightleg_ibus_value = adc_rightleg_ibus_value;
            this.adc_waist_ibus_value = adc_waist_ibus_value;
            this.adc_charge_det_value = adc_charge_det_value;
            this.adc_vdc1_value = adc_vdc1_value;
            this.adc_mos_temp = adc_mos_temp;
            this.adc_1v5 = adc_1v5;
            this.temptature = temptature;
            this.vrefint = vrefint;
            this.adc_x86_ibus_value = adc_x86_ibus_value;
            this.adc_rk_ibus_value = adc_rk_ibus_value;
            this.adc_3vref_value = adc_3vref_value;
            this.err_code = err_code;
            this.second = second;
            this.minute = minute;
            this.hour = hour;
            this.day = day;
            this.month = month;
            this.year = year;
        }

        public static InnerDataMsg Deserialize(MessageDeserializer deserializer) => new InnerDataMsg(deserializer);

        private InnerDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.adc_orin_value);
            deserializer.Read(out this.adc_orin_ibus_value);
            deserializer.Read(out this.adc_arm_ibus_value);
            deserializer.Read(out this.adc_ibus_value);
            deserializer.Read(out this.adc_leftleg_ibus_value);
            deserializer.Read(out this.adc_rightleg_ibus_value);
            deserializer.Read(out this.adc_waist_ibus_value);
            deserializer.Read(out this.adc_charge_det_value);
            deserializer.Read(out this.adc_vdc1_value);
            deserializer.Read(out this.adc_mos_temp);
            deserializer.Read(out this.adc_1v5);
            deserializer.Read(out this.temptature);
            deserializer.Read(out this.vrefint);
            deserializer.Read(out this.adc_x86_ibus_value);
            deserializer.Read(out this.adc_rk_ibus_value);
            deserializer.Read(out this.adc_3vref_value);
            deserializer.Read(out this.err_code);
            deserializer.Read(out this.second);
            deserializer.Read(out this.minute);
            deserializer.Read(out this.hour);
            deserializer.Read(out this.day);
            deserializer.Read(out this.month);
            deserializer.Read(out this.year);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.adc_orin_value);
            serializer.Write(this.adc_orin_ibus_value);
            serializer.Write(this.adc_arm_ibus_value);
            serializer.Write(this.adc_ibus_value);
            serializer.Write(this.adc_leftleg_ibus_value);
            serializer.Write(this.adc_rightleg_ibus_value);
            serializer.Write(this.adc_waist_ibus_value);
            serializer.Write(this.adc_charge_det_value);
            serializer.Write(this.adc_vdc1_value);
            serializer.Write(this.adc_mos_temp);
            serializer.Write(this.adc_1v5);
            serializer.Write(this.temptature);
            serializer.Write(this.vrefint);
            serializer.Write(this.adc_x86_ibus_value);
            serializer.Write(this.adc_rk_ibus_value);
            serializer.Write(this.adc_3vref_value);
            serializer.Write(this.err_code);
            serializer.Write(this.second);
            serializer.Write(this.minute);
            serializer.Write(this.hour);
            serializer.Write(this.day);
            serializer.Write(this.month);
            serializer.Write(this.year);
        }

        public override string ToString()
        {
            return "InnerDataMsg: " +
            "\nadc_orin_value: " + adc_orin_value.ToString() +
            "\nadc_orin_ibus_value: " + adc_orin_ibus_value.ToString() +
            "\nadc_arm_ibus_value: " + adc_arm_ibus_value.ToString() +
            "\nadc_ibus_value: " + adc_ibus_value.ToString() +
            "\nadc_leftleg_ibus_value: " + adc_leftleg_ibus_value.ToString() +
            "\nadc_rightleg_ibus_value: " + adc_rightleg_ibus_value.ToString() +
            "\nadc_waist_ibus_value: " + adc_waist_ibus_value.ToString() +
            "\nadc_charge_det_value: " + adc_charge_det_value.ToString() +
            "\nadc_vdc1_value: " + adc_vdc1_value.ToString() +
            "\nadc_mos_temp: " + adc_mos_temp.ToString() +
            "\nadc_1v5: " + adc_1v5.ToString() +
            "\ntemptature: " + temptature.ToString() +
            "\nvrefint: " + vrefint.ToString() +
            "\nadc_x86_ibus_value: " + adc_x86_ibus_value.ToString() +
            "\nadc_rk_ibus_value: " + adc_rk_ibus_value.ToString() +
            "\nadc_3vref_value: " + adc_3vref_value.ToString() +
            "\nerr_code: " + err_code.ToString() +
            "\nsecond: " + second.ToString() +
            "\nminute: " + minute.ToString() +
            "\nhour: " + hour.ToString() +
            "\nday: " + day.ToString() +
            "\nmonth: " + month.ToString() +
            "\nyear: " + year.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
