//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Shm
{
    [Serializable]
    public class HeaderMsg : Message
    {
        public const string k_RosMessageName = "shm_msgs/Header";
        public override string RosMessageName => k_RosMessageName;

        //  Two-integer timestamp that is expressed as seconds and nanoseconds.
        public BuiltinInterfaces.TimeMsg stamp;
        //  Transform frame with which this data is associated.
        public StringMsg frame_id;

        public HeaderMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.frame_id = new StringMsg();
        }

        public HeaderMsg(BuiltinInterfaces.TimeMsg stamp, StringMsg frame_id)
        {
            this.stamp = stamp;
            this.frame_id = frame_id;
        }

        public static HeaderMsg Deserialize(MessageDeserializer deserializer) => new HeaderMsg(deserializer);

        private HeaderMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.frame_id = StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.frame_id);
        }

        public override string ToString()
        {
            return "HeaderMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nframe_id: " + frame_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
