//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Shm
{
    [Serializable]
    public class StringMsg : Message
    {
        public const string k_RosMessageName = "shm_msgs/String";
        public override string RosMessageName => k_RosMessageName;

        public byte[] data;
        public byte size = 0;
        public const byte MAX_SIZE = 255;

        public StringMsg()
        {
            this.data = new byte[256];
        }

        public StringMsg(byte[] data, byte size)
        {
            this.data = data;
            this.size = size;
        }

        public static StringMsg Deserialize(MessageDeserializer deserializer) => new StringMsg(deserializer);

        private StringMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(byte), 256);
            deserializer.Read(out this.size);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
            serializer.Write(this.size);
        }

        public override string ToString()
        {
            return "StringMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\nsize: " + size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
