//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosa
{
    [Serializable]
    public class NodeStateMsg : Message
    {
        public const string k_RosMessageName = "rosa_msgs/NodeState";
        public override string RosMessageName => k_RosMessageName;

        //  frame_id 填充节点名称，stamp 填充状态时间戳
        public Std.HeaderMsg header;
        //  状态码
        //  共计 7 位数
        //    1. 状态类型标识符（1-3 表示一般状态，4-6 表示警告状态，7-9 表示错误状态）
        //    2. 模块标识符
        //  3-4. 子模块标识符
        //  5-7. 实际状态码
        public uint state;
        //  description 状态描述
        public string desc;
        //  自定义的状态类型
        public string msg_type;

        public NodeStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.state = 0;
            this.desc = "";
            this.msg_type = "";
        }

        public NodeStateMsg(Std.HeaderMsg header, uint state, string desc, string msg_type)
        {
            this.header = header;
            this.state = state;
            this.desc = desc;
            this.msg_type = msg_type;
        }

        public static NodeStateMsg Deserialize(MessageDeserializer deserializer) => new NodeStateMsg(deserializer);

        private NodeStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
            deserializer.Read(out this.desc);
            deserializer.Read(out this.msg_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
            serializer.Write(this.desc);
            serializer.Write(this.msg_type);
        }

        public override string ToString()
        {
            return "NodeStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString() +
            "\ndesc: " + desc.ToString() +
            "\nmsg_type: " + msg_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
