//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SysTask
{
    [Serializable]
    public class AsrMsg : Message
    {
        public const string k_RosMessageName = "sys_task_msgs/Asr";
        public override string RosMessageName => k_RosMessageName;

        public string text;
        // 文本内容
        public string language;
        // 语音类型
        public string emotion;
        // 情感，暂时未用到
        public string status;
        // 状态，暂时未使用
        public int wordnum;
        // 几个汉字或者几个单词

        public AsrMsg()
        {
            this.text = "";
            this.language = "";
            this.emotion = "";
            this.status = "";
            this.wordnum = 0;
        }

        public AsrMsg(string text, string language, string emotion, string status, int wordnum)
        {
            this.text = text;
            this.language = language;
            this.emotion = emotion;
            this.status = status;
            this.wordnum = wordnum;
        }

        public static AsrMsg Deserialize(MessageDeserializer deserializer) => new AsrMsg(deserializer);

        private AsrMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.text);
            deserializer.Read(out this.language);
            deserializer.Read(out this.emotion);
            deserializer.Read(out this.status);
            deserializer.Read(out this.wordnum);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.text);
            serializer.Write(this.language);
            serializer.Write(this.emotion);
            serializer.Write(this.status);
            serializer.Write(this.wordnum);
        }

        public override string ToString()
        {
            return "AsrMsg: " +
            "\ntext: " + text.ToString() +
            "\nlanguage: " + language.ToString() +
            "\nemotion: " + emotion.ToString() +
            "\nstatus: " + status.ToString() +
            "\nwordnum: " + wordnum.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
