//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McState
{
    [Serializable]
    public class RobotStateMsg : Message
    {
        public const string k_RosMessageName = "mc_state_msgs/RobotState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Sensor.JointStateMsg joint_states;
        public Sensor.ImuMsg[] imu_states;
        public Geometry.WrenchStampedMsg[] ft_states;

        public RobotStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.joint_states = new Sensor.JointStateMsg();
            this.imu_states = new Sensor.ImuMsg[0];
            this.ft_states = new Geometry.WrenchStampedMsg[0];
        }

        public RobotStateMsg(Std.HeaderMsg header, Sensor.JointStateMsg joint_states, Sensor.ImuMsg[] imu_states, Geometry.WrenchStampedMsg[] ft_states)
        {
            this.header = header;
            this.joint_states = joint_states;
            this.imu_states = imu_states;
            this.ft_states = ft_states;
        }

        public static RobotStateMsg Deserialize(MessageDeserializer deserializer) => new RobotStateMsg(deserializer);

        private RobotStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.joint_states = Sensor.JointStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.imu_states, Sensor.ImuMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.ft_states, Geometry.WrenchStampedMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.joint_states);
            serializer.WriteLength(this.imu_states);
            serializer.Write(this.imu_states);
            serializer.WriteLength(this.ft_states);
            serializer.Write(this.ft_states);
        }

        public override string ToString()
        {
            return "RobotStateMsg: " +
            "\nheader: " + header.ToString() +
            "\njoint_states: " + joint_states.ToString() +
            "\nimu_states: " + System.String.Join(", ", imu_states.ToList()) +
            "\nft_states: " + System.String.Join(", ", ft_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
