//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class ArmTaskResult : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/ArmTask";
        public override string RosMessageName => k_RosMessageName;

        //  Result motion execute result
        public Rosa.NodeStateMsg state;

        public ArmTaskResult()
        {
            this.state = new Rosa.NodeStateMsg();
        }

        public ArmTaskResult(Rosa.NodeStateMsg state)
        {
            this.state = state;
        }

        public static ArmTaskResult Deserialize(MessageDeserializer deserializer) => new ArmTaskResult(deserializer);

        private ArmTaskResult(MessageDeserializer deserializer)
        {
            this.state = Rosa.NodeStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ArmTaskResult: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
