//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class ArmTaskGoal : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/ArmTask";
        public override string RosMessageName => k_RosMessageName;

        //  motion id indicates different motions
        public string task_name;
        //  motion arguments packed in a json string
        //  corresponding profile.json file describe how to parse there json arguments
        public string yaml_args = "";

        public ArmTaskGoal()
        {
            this.task_name = "";
        }

        public ArmTaskGoal(string task_name, string yaml_args)
        {
            this.task_name = task_name;
            this.yaml_args = yaml_args;
        }

        public static ArmTaskGoal Deserialize(MessageDeserializer deserializer) => new ArmTaskGoal(deserializer);

        private ArmTaskGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_name);
            deserializer.Read(out this.yaml_args);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_name);
            serializer.Write(this.yaml_args);
        }

        public override string ToString()
        {
            return "ArmTaskGoal: " +
            "\ntask_name: " + task_name.ToString() +
            "\nyaml_args: " + yaml_args.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
