//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class ArmTaskFeedback : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/ArmTask";
        public override string RosMessageName => k_RosMessageName;

        //  Feedback
        public Rosa.NodeStateMsg state;
        public double total_time;
        public double current_time;

        public ArmTaskFeedback()
        {
            this.state = new Rosa.NodeStateMsg();
            this.total_time = 0.0;
            this.current_time = 0.0;
        }

        public ArmTaskFeedback(Rosa.NodeStateMsg state, double total_time, double current_time)
        {
            this.state = state;
            this.total_time = total_time;
            this.current_time = current_time;
        }

        public static ArmTaskFeedback Deserialize(MessageDeserializer deserializer) => new ArmTaskFeedback(deserializer);

        private ArmTaskFeedback(MessageDeserializer deserializer)
        {
            this.state = Rosa.NodeStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.total_time);
            deserializer.Read(out this.current_time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.total_time);
            serializer.Write(this.current_time);
        }

        public override string ToString()
        {
            return "ArmTaskFeedback: " +
            "\nstate: " + state.ToString() +
            "\ntotal_time: " + total_time.ToString() +
            "\ncurrent_time: " + current_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
