//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class GaitModeSwitchRequest : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/GaitModeSwitch";
        public override string RosMessageName => k_RosMessageName;

        public const int STOP = 1;
        public const int STAND = 2;
        public const int DYNAMIC = 3;
        public int mode;

        public GaitModeSwitchRequest()
        {
            this.mode = 0;
        }

        public GaitModeSwitchRequest(int mode)
        {
            this.mode = mode;
        }

        public static GaitModeSwitchRequest Deserialize(MessageDeserializer deserializer) => new GaitModeSwitchRequest(deserializer);

        private GaitModeSwitchRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "GaitModeSwitchRequest: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
