//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class GaitModeSwitchResponse : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/GaitModeSwitch";
        public override string RosMessageName => k_RosMessageName;

        public Rosa.NodeStateMsg state;

        public GaitModeSwitchResponse()
        {
            this.state = new Rosa.NodeStateMsg();
        }

        public GaitModeSwitchResponse(Rosa.NodeStateMsg state)
        {
            this.state = state;
        }

        public static GaitModeSwitchResponse Deserialize(MessageDeserializer deserializer) => new GaitModeSwitchResponse(deserializer);

        private GaitModeSwitchResponse(MessageDeserializer deserializer)
        {
            this.state = Rosa.NodeStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GaitModeSwitchResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
