//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class WalkerMotionRequest : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/WalkerMotion";
        public override string RosMessageName => k_RosMessageName;

        //  motion id indicates different motions
        public string motion_id;
        //  motion arguments packed in a json string
        //  corresponding profile.json file describe how to parse there json arguments
        public string json_args;
        //  'start' or 'stop' motion
        public const string CMD_START = "start";
        public const string CMD_STOP = "stop";
        public string cmd;

        public WalkerMotionRequest()
        {
            this.motion_id = "";
            this.json_args = "";
            this.cmd = "";
        }

        public WalkerMotionRequest(string motion_id, string json_args, string cmd)
        {
            this.motion_id = motion_id;
            this.json_args = json_args;
            this.cmd = cmd;
        }

        public static WalkerMotionRequest Deserialize(MessageDeserializer deserializer) => new WalkerMotionRequest(deserializer);

        private WalkerMotionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motion_id);
            deserializer.Read(out this.json_args);
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motion_id);
            serializer.Write(this.json_args);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "WalkerMotionRequest: " +
            "\nmotion_id: " + motion_id.ToString() +
            "\njson_args: " + json_args.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
