//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class WalkerMotionResponse : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/WalkerMotion";
        public override string RosMessageName => k_RosMessageName;

        //  motion execute result
        public bool ok;
        //  error message
        public string message;

        public WalkerMotionResponse()
        {
            this.ok = false;
            this.message = "";
        }

        public WalkerMotionResponse(bool ok, string message)
        {
            this.ok = ok;
            this.message = message;
        }

        public static WalkerMotionResponse Deserialize(MessageDeserializer deserializer) => new WalkerMotionResponse(deserializer);

        private WalkerMotionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "WalkerMotionResponse: " +
            "\nok: " + ok.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
