//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class JointCommandMsg : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/JointCommand";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public int[] mode;
        public double[] position;
        public double[] velocity;
        public double[] torque;
        public double[] acceleration;
        public string[] names;
        public double[] kp;
        public double[] kd;
        public const int POSITION_MODE = 1;
        public const int VELOCITY_MODE = 2;
        public const int TORQUE_MODE = 3;
        public const int RAW_POSITION_MODE = 4;

        public JointCommandMsg()
        {
            this.header = new Std.HeaderMsg();
            this.mode = new int[0];
            this.position = new double[0];
            this.velocity = new double[0];
            this.torque = new double[0];
            this.acceleration = new double[0];
            this.names = new string[0];
            this.kp = new double[0];
            this.kd = new double[0];
        }

        public JointCommandMsg(Std.HeaderMsg header, int[] mode, double[] position, double[] velocity, double[] torque, double[] acceleration, string[] names, double[] kp, double[] kd)
        {
            this.header = header;
            this.mode = mode;
            this.position = position;
            this.velocity = velocity;
            this.torque = torque;
            this.acceleration = acceleration;
            this.names = names;
            this.kp = kp;
            this.kd = kd;
        }

        public static JointCommandMsg Deserialize(MessageDeserializer deserializer) => new JointCommandMsg(deserializer);

        private JointCommandMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.mode, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.position, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.velocity, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.torque, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.acceleration, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.kp, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.kd, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.mode);
            serializer.Write(this.mode);
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.WriteLength(this.velocity);
            serializer.Write(this.velocity);
            serializer.WriteLength(this.torque);
            serializer.Write(this.torque);
            serializer.WriteLength(this.acceleration);
            serializer.Write(this.acceleration);
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.kp);
            serializer.Write(this.kp);
            serializer.WriteLength(this.kd);
            serializer.Write(this.kd);
        }

        public override string ToString()
        {
            return "JointCommandMsg: " +
            "\nheader: " + header.ToString() +
            "\nmode: " + System.String.Join(", ", mode.ToList()) +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\nvelocity: " + System.String.Join(", ", velocity.ToList()) +
            "\ntorque: " + System.String.Join(", ", torque.ToList()) +
            "\nacceleration: " + System.String.Join(", ", acceleration.ToList()) +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nkp: " + System.String.Join(", ", kp.ToList()) +
            "\nkd: " + System.String.Join(", ", kd.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
