//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class JointCmdMsg : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/JointCmd";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte BEGIN = -1;
        public const sbyte MODE_EFFORT = 0;
        public const sbyte MODE_VELOCITY = 1;
        public const sbyte MODE_POSITION = 2;
        public const sbyte CUSTOM_MODE_1 = 7;
        public const sbyte CUSTOM_MODE_2 = 8;
        public const sbyte CUSTOM_MODE_3 = 9;
        public string name;
        public sbyte control_mode;
        public double position;
        public double velocity;
        public double effort;
        public double v1;
        public double v2;
        public double v3;

        public JointCmdMsg()
        {
            this.name = "";
            this.control_mode = 0;
            this.position = 0.0;
            this.velocity = 0.0;
            this.effort = 0.0;
            this.v1 = 0.0;
            this.v2 = 0.0;
            this.v3 = 0.0;
        }

        public JointCmdMsg(string name, sbyte control_mode, double position, double velocity, double effort, double v1, double v2, double v3)
        {
            this.name = name;
            this.control_mode = control_mode;
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
            this.v1 = v1;
            this.v2 = v2;
            this.v3 = v3;
        }

        public static JointCmdMsg Deserialize(MessageDeserializer deserializer) => new JointCmdMsg(deserializer);

        private JointCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.control_mode);
            deserializer.Read(out this.position);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.effort);
            deserializer.Read(out this.v1);
            deserializer.Read(out this.v2);
            deserializer.Read(out this.v3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.control_mode);
            serializer.Write(this.position);
            serializer.Write(this.velocity);
            serializer.Write(this.effort);
            serializer.Write(this.v1);
            serializer.Write(this.v2);
            serializer.Write(this.v3);
        }

        public override string ToString()
        {
            return "JointCmdMsg: " +
            "\nname: " + name.ToString() +
            "\ncontrol_mode: " + control_mode.ToString() +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\neffort: " + effort.ToString() +
            "\nv1: " + v1.ToString() +
            "\nv2: " + v2.ToString() +
            "\nv3: " + v3.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
