//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.McTask
{
    [Serializable]
    public class RobotCommandMsg : Message
    {
        public const string k_RosMessageName = "mc_task_msgs/RobotCommand";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public JointCmdMsg[] joint_cmd;

        public RobotCommandMsg()
        {
            this.header = new Std.HeaderMsg();
            this.joint_cmd = new JointCmdMsg[0];
        }

        public RobotCommandMsg(Std.HeaderMsg header, JointCmdMsg[] joint_cmd)
        {
            this.header = header;
            this.joint_cmd = joint_cmd;
        }

        public static RobotCommandMsg Deserialize(MessageDeserializer deserializer) => new RobotCommandMsg(deserializer);

        private RobotCommandMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.joint_cmd, JointCmdMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.joint_cmd);
            serializer.Write(this.joint_cmd);
        }

        public override string ToString()
        {
            return "RobotCommandMsg: " +
            "\nheader: " + header.ToString() +
            "\njoint_cmd: " + System.String.Join(", ", joint_cmd.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
